_wandb:
    value:
        cli_version: 0.22.3
        code_path: code/experiments/train_encoder.py
        e:
            iktj1860hvanps7del4xz7uf86bf1qj4:
                args:
                    - --batch-size=128
                    - --dropout=0
                    - --embed-dim=128
                    - --encoder-type=transformer
                    - --heads-per-patch=1
                    - --hidden-dim=256
                    - --lr=0.00013829952679002717
                    - --max-epochs=100
                    - --model-name=gpt2
                    - --n-attn-heads=2
                    - --n-cv-folds=5
                    - --n-hidden-layers=2
                    - --objective-alpha-weight=0.5
                    - --objective-recon-weight=0
                    - --objective-task-weight=1
                    - --patch-depth=1
                    - --weight-decay=0.004425627078068696
                codePath: experiments/train_encoder.py
                codePathLocal: experiments/train_encoder.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "982240026624"
                        used: "876193349632"
                email: s.mander3@lancaster.ac.uk
                executable: /home/user/miniconda3/envs/opence/bin/python
                git:
                    commit: dc31b6843bd80e4a5d7c6636df26eb56fa4e83c5
                    remote: https://github.com/st7ma784/EEGSCRFP.git
                host: scc-ws-01
                memory:
                    total: "33591480320"
                os: Linux-6.17.0-19-generic-x86_64-with-glibc2.39
                program: /home/user/EEGViewer/EEGSCRFP/experiments/train_encoder.py
                python: CPython 3.10.19
                root: /home/user/EEGViewer/EEGSCRFP
                startedAt: "2026-04-11T06:31:14.589563Z"
                writerId: iktj1860hvanps7del4xz7uf86bf1qj4
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 2
                - 13
                - 14
                - 16
                - 62
            "4": 3.10.19
            "5": 0.22.3
            "6": 5.1.0
            "12": 0.22.3
            "13": linux-x86_64
alpha:
    value: 1
batch_size:
    value: 128
cache_dir:
    value: outputs
data_dir:
    value: null
dropout:
    value: 0
embed_dim:
    value: 128
encoder_type:
    value: transformer
heads_per_patch:
    value: 1
hidden_dim:
    value: 256
lr:
    value: 0.00013829952679002717
max_epochs:
    value: 100
model_name:
    value: gpt2
n_attn_heads:
    value: 2
n_cv_folds:
    value: 5
n_hidden_layers:
    value: 2
no_cache:
    value: false
num_prompts:
    value: 60
objective_alpha_weight:
    value: 0.5
objective_recon_weight:
    value: 0
objective_task_weight:
    value: 1
patch_depth:
    value: 1
wandb_project:
    value: null
weight_decay:
    value: 0.004425627078068696
