wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.1
embed_dim:
  value: 64
encoder_type:
  value: transformer
heads_per_patch:
  value: 1
hidden_dim:
  value: 256
lr:
  value: 0.00023525930099995573
max_epochs:
  value: 100
model_name:
  value: gpt2
n_attn_heads:
  value: 8
n_cv_folds:
  value: 5
n_hidden_layers:
  value: 1
objective_alpha_weight:
  value: 0.5
objective_recon_weight:
  value: 1
objective_task_weight:
  value: 1
patch_depth:
  value: 1
weight_decay:
  value: 0.0005276815955662104
